# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - androidbuild
  - androidtest
  - mavenbuild
  - maventest
  - autodeploy

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
maven-build:
  stage: mavenbuild
  tags:
    - backend_tag
  script:
    - cd Backend/CatchTheCacheServer
    - mvn package -B
  only:
    refs:
      - master
      - dev
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - backend_tag
  script:
    - cd Backend/CatchTheCacheServer
    - mvn test
  only:
    refs:
      - master
      - dev
  artifacts:
    paths:
      - Backend/CatchTheCacheServer/target/*.jar
# Below stage builds, deploys and executes the jar as service.
# Make sure there is /target directory in your server, else script will fail, or use any other folder you like.
# If you are changing the folder, reflect the change in systemd-web-demo service too.
autoDeploy:
  stage: autodeploy
  tags:
   - backend_tag
  script:
    - cd Backend/CatchTheCacheServer
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - master
      - dev

    
# To build android projects
# Notice that we cd into Frontend/CatchTheCacheAndroid folder which contains all Android files before building apk.    
# Ensure the tag matches with the tag created for Android runner
# Android runner should have docker as executor.
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CatchTheCacheAndroid/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/CatchTheCacheAndroid
    - ./gradlew assemble
  only:
    refs:
      - master
      - dev
  artifacts:
    paths:
    - Frontend/CatchTheCacheAndroid/app/build/outputs/
    
# To run Android unit tests.   
unitTests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CatchTheCacheAndroid/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/CatchTheCacheAndroid
    - ./gradlew test
  only:
    refs:
      - master
      - dev
